### ISSUE TITLE
Не отображаются подстрочные индексы

### ISSUE THREAD

**Issue by Fersol** [Nikscorp/gos#4]
В билете 10 есть использование подстрочной формулы T~1~, в полученном документе так и отображается, хотя markdown разрешает в таком виде делать подстрочные индексы таким способом.

**Comment by Nikscorp** [comment]
Как видишь не разрешает, это расширение md, которое везде работает по разному. В гитхабе как видишь, это зачеркивает тек~ст~. Можно или запариться и добавить это в gitbook или поправить на latex в этих местах `$T_{123}$`.
